import { Inter } from "next/font/google";
import "./globals.css";
import AuthModalContextProvider from "@/store/auth-modal-context";
import SignupModal from "@/components/auth/signup-modal";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Best YouTube Thumbnails",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthModalContextProvider>
          {children}
          <SignupModal />
        </AuthModalContextProvider>
      </body>
    </html>
  );
}
